### ISSUE TITLE
UL / OL List behaviour mega issue.

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3772]
Lists (both unordered and ordered) in Etherpad have some user experience quirks I want to bring all into one megathread.

I'm going to document all behavior that works at present:

## Frontend
- [x] ``Ctrl Shift 1`` should insert Ordered list
  - [x] Test Coverage 
- [x] ``Ctrl Shift N`` should insert unordered list
  - [x] Test Coverage
- [x] Pressing Enter on OL should keep OL
  - [x] Test Coverage
- [x] Pressing Enter on UL should keep UL
  - [x] Test Coverage
- [x] Press ``Tab`` should indent
  - [x] Test Coverage
- [x] Press ``Shift Tab`` should outdent
  - [x] Test Coverage
- [x] Pressing Indent icon should increase list level
  - [x] Test Coverage
- [x] Pressing de-Indent icon should outdent list level
  - [x] Test Coverage
- [x] BUG: Pressing List Icon should remove list: #2812 - Resolved with https://github.com/ether/etherpad-lite/pull/3842
   - [x] Test Coverage has a PR
- [ ] FEATURE REQUEST: ``Shift&Alt Up/Down`` to move items up/down lists
  - [ ] Test Coverage
- [ ] PERFORMANCE (I can't optimize this further): Big nested lists are having performance issues on Firefox #2297
  - [ ]  Test Coverage
- [ ] QUIRK (I can't fix) Wrapped lines of list items don't intent to match first line #2581
  - [ ] Test Coverage
- [x] BUG: Chrome pasting OLs #2412 
  - [ ] Test Coverage (not sure it's possible).
- [x] BUG: Copy/Paste from Etherpad to other editors doesn't keep OLs #2941 
  - [ ] Test Coverage (not sure it's possible).
- [ ] BUG: Long list wrapped line items get new numbers #2055
  - [ ] Test Coverage

## Backend

- [x] BUG: Exported/Imported HTML should match what's rendered on screen.  #3620
  - [x] Test Coverage
- [x] BUG: White space or text without being a list should not create list items #3620 <-- solved in https://github.com/ether/etherpad-lite/pull/3879
   - [x] Test Coverage
- [x] BUG: Ordered Lists exports doesn't prefix correct number upon import and export: #3450 & #3447 -- Covered by https://github.com/ether/etherpad-lite/pull/3877
  - [x] Import
  - [x] Export
  - [x] Test Coverage
- [ ] BUG: New lines shouldn't reset line numbering: #2194 <-- I can't fix in this round. -- This is more of a feature request, new lines that are bullets wont change numbering.  I left comments in the code for how someone can implement this and we can look at it in the future but it's potentially a breaking change (as it's a change in UX).
  - [x] Test Coverage (but commented out)

## Discussion
- [ ] QUIRK: "Four spaces" as a pre-fix for lists is weird - see if we can drop it
  - [ ] Test Coverage

Milestone todos:
- [ ] Test coverage for expected behavior.

**Comment by JohnMcLear** [comment]
My plan is to do test coverage for bugs.  These can then be worked against by someone who wants to refactor ``contentcollector.js`` and ``ace2_inner.js``

**Comment by JohnMcLear** [comment]
I decided NOT to do test coverage for keystroke to move line up/down because while it's a "nice to have" IMHO it's not required as part of the fixes for list support.  Everything is covered so I will leave this PR open so someone can use it to test their changes against.  I'm unassigning myself now my work here is done :)

**Comment by JohnMcLear** [comment]
https://twitter.com/Kvantti/status/1244285020228984834Ñ

**Comment by JohnMcLear** [comment]
Ready for initial testing.

https://github.com/ether/etherpad-lite/pull/3877

**Comment by JohnMcLear** [comment]
All merged :)
