### ISSUE TITLE
log4js needs to be upgraded. Breaking change in the config?

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3843]
The current Etherpad development version (3edd727a943c, **1.8.0+**) version uses a very old version of [log4js](https://github.com/log4js-node/log4js-node) ([**0.6.35**](https://github.com/log4js-node/log4js-node/releases/tag/v0.6.35), from 2016-04-15).

Among other things, this implies (as noted by @anttiviljami [here](https://github.com/ether/etherpad-lite/issues/3834#issuecomment-609938283)), that **CustomErrors are not displayed in the logs**.

In their place we see `{ inspect: [Function: inspect] }`.

This would be solved by a much needed upgrade of log4js.
Unfortunately, `settings.json` directly exposes the internal log4js configuration API:

https://github.com/ether/etherpad-lite/blob/3edd727a943cfa94bb200c8d7d743e1ecce31f58/settings.json.template#L451-L501

So, if we upgraded without taking precautions, existing configuration files would lose compatibility.

**TODO**:
- [ ] study if/how the configuration syntax has changed from **0.6.35** to **6.1.2** (latest current version)
- [ ] how would this impact existing installations?
- [ ] study a migration plan.
      1. Make a compatibility layer in the code?
      2. Write a small migration tool for the configuration file?
      3. Something else?
