### ISSUE TITLE
Read-only user accounts

### ISSUE THREAD

**Issue by rhansen** [ether/etherpad-lite#4325]
I would like to add support for read-only users and read-only access to specific pads. Users would be able to use the normal pad URL (not the read-only pad URL) but still be restricted to read-only access.

I have already implemented this in my fork of the etherpad-lite repository. [My read-only-user branch](https://github.com/rhansen/etherpad-lite/tree/read-only-user) introduces the following two new features:
  * Plugins can use the `authorize` hook to grant read-only or modify-only (no create) access on a per-user, per-pad basis by returning one of `false`, `'readOnly'`, `'modify'`, `'create'`, or `true` (same as `'create'`).
  * Users can be given read-only or modify-only (no create) access in `settings.json` or in an `authenticate` plugin. For example:
    ```json
      "users": {
        "guest": {
          "password": "guest",
          "readOnly": true
        },
        "user": {
          "password": "mypassword",
          "canCreate": false
        }
      },
    ```

Most of my recent pull requests were done to prepare for these new features. Many bug fix, cleanup, and refactor commits still remain. I will update the following list as PRs are created and merged.

  * [x] Document the authenticate hook #4232 
  * [x] docs: Document the authorize hook #4233
  * [x] webaccess: Various cleanups #4248 
  * [x] User list: Use flexbox for #myuser div #4246 
  * [x] PadMessageHandler: Pass socket.io Socket object to clientVars hook #4245 
  * [x] cleanup: Delete redundant token2author DB save #4241 
  * [x] docs: Document the authFailure hook #4247 
  * [x] docs: Revise hooks overview section #4250 
  * [x] hooks: Always return a list from `aCallFirst` and `callFirst` #4251 
  * [x] webaccess: Always sleep for 1s before returning HTTP 401 #4249 
  * [x] PadMessageHandler: Delete redundant check #4253 
  * [x] pluginfw: Always include the function name in `hook_fn_name` #4252 
  * [x] SecurityManager: Simplify checkAccess #4261 
  * [x] Revert "Delete redundant token2author DB save" #4263 
  * [x] plugins: Move plugin definitions to avoid monkey patching #4259 
  * [x] hooks: New mechanism to deprecate hooks #4255 
  * [x] plugins: Fix type typo #4258 
  * [x] SecurityManager: Use constants for returned rejections #4265 
  * [x] import: Use the correct author ID when using sessions #4264 
  * [x] Use `null`, not `"null"`, if `sessionID` cookie doesn't exist #4280 
  * [x] PadMessageHandler: Various cleanups #4260 
  * [x] SecurityManager: Refactor checkAccess for readability, correctness #4282 
  * [x] security: Fix authentication bypass vulnerability #4287 
  * [x] security: Check authentication in SecurityManager checkAccess #4290 
  * [x] i18n: Improve error logging when language JSON read fails #4299 
  * [x] PadMessageHandler: Move code out of unnecessary closure #4283 
  * [x] docs: Revise documentation for handleMessage and handleMessageSecurity #4277 
  * [x] webaccess: Enforce creation of `req.session.user` by authn plugins #4270 
  * [x] webaccess: Pass `settings.users` to the authenticate hook #4269 
  * [x] webaccess: Factor out common code #4296 
  * [x] tests: Add authentication, authorization bypass tests #4289 
  * [x] PadMessageHandler: Move code out of unnecessary closure (again) #4302 
  * [x] PadMessageHandler: Fix assignment to const variable #4303 
  * [x] webaccess: Fix syntax error (missing close curly brace) #4306 
  * [x] tests: Use wtfnode to determine why mocha isn't exiting #4304 
  * [x] security: Fix authorization bypass vulnerability #4305 
  * [x] socketio: Use Error objects for socket.io connection errors #4288 
  * [x] SessionManager: Fix session expiration check #4324 
  * [x] SessionStore: Various cleanups and bug fixes #4328 
  * [x] utils: Fix promise creation accounting bug in promises.timesLimit #4312
  * [x] Refactor startup/shutdown for tests #4329
  * [x] async-ify more functions, and await completion #4313
  * [x] PadMessageHandler: Make sessioninfo tracking more robust #4307
  * [x] PadMessageHandler: Move handleMessage hooks after access check #4336 
  * [x] webaccess: Return 401 for authn failure, 403 for authz failure #4254
  * [x] security: Don't require express_sid if authn not required #4342 
  * [x] Revert "tests: Use wtfnode to determine why mocha isn't exiting" #4315
  * [x] security: Fix authz check for pad names with encoded characters #4346 
  * [x] PadMessageHandler: Block Promise resolution until message is handled #4349 
  * [x] security: Enable authorize plugins to grant modify-only access #4343 
  * [x] PadMessageHandler: Avoid redundant access checks #4354 
  * [x] Fix typo in session check (sesion -> session) #4357 
  * [x] webaccess: Split authFailure hook into authnFailure and authzFailure #4348 
  * [x] PadMessageHandler: Logging improvements #4356 
  * [x] webaccess: Log all authentication successes/failures #4358 
  * [x] webaccess: Move pre-authn authz check to a separate hook #4362 
  * [x] security: Enable authorize plugins to grant read-only access #4365 
  * [ ] webaccess: Log hook errors #4367 
  * [ ] webaccess: Exempt `/favicon.ico` and `/locales.json` from auth checks #4371 
  * [ ] New user-specific `readOnly` and `canCreate` settings #4370 

Not all of the above commits/PRs are necessary for read-only user access, but they make it easier to write plugins that take advantage of the new features.
