### ISSUE TITLE
Better handling of reconnects

### ISSUE THREAD

**Issue by rhansen** [ether/etherpad-lite#4331]
Issue #3830 describes a problem where pads silently disconnect when the browser suspends a background tab. PR #3868 added a workaround, but that workaround has a couple of significant drawbacks:
  * If the server (or browser?) is slow enough, visiting a different URL in the same browser tab can trigger a disconnect which causes the `document.location=document.location` line to trigger a reload of the original URL before the new URL has a chance to load. In my use case, this caused a link I added to pads (that goes to a `/login` page) to not work reliably.
  * If the pad takes a long time to load (more than the socket.io ping timeout) then the pad will enter an infinite reload loop.

I think I have figured out why the original bug existed, so I think we can fix this issue properly now. To make the commit history easier to read I'm going to split the fix across a few PRs:

  * [x] Add a new 'rejected' disconnect reason #4330 
  * [x] PadMessageHandler: Always save the author ID in the session info #4353 
  * [ ] pad: Revert back to sending CLIENT_READY on reconnect #4355

**Comment by rhansen** [comment]
FYI, I reproduced the disconnects on Linux by doing the following:

  1. Run: `killall -STOP node`
  2. Wait for the client to notice that it can no longer ping the server and enter the reconnecting state
  3. Run: `killall -CONT node`
