### ISSUE TITLE
CI Release script todo

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4819]
In a bid to get more CI and autopublishing on successful ``develop`` branch tests the following tasks require completion:

## release.js
- [ ] On clean etherpad-lite repo need to ``git checkout master && git checkout develop && cd src && npm ci``
- [ ] clone docs repo - ``cd .. && git clone git@github.com:ether/ether.github.com.git``
- [ ] bump version # in ``index.html`` in ``ether.github.com``, simple `/g/oldversion/newversion``
- [ ] Expects ``gpg`` setup/key available ( can we use Github secrets?) 
- [ ] Windows zip and exe should be taken from CI - https://github.com/marketplace/actions/upload-files-to-a-github-release is the docs for uploading a built release to github release

Probably hard to do:
- [ ] Changelog automation...

**Comment by JohnMcLear** [comment]
@rhansen I can do this if you want but it might break the flow of you checking things are as expected.

I want to be able to build and release from CI so gpg is a no go w/ out some hacking.

https://github.com/marketplace/actions/upload-files-to-a-github-release is the docs for uploading a built release to github release, we would only do this if all tests pass, release script runs cleanly and we're testing develop branch..
